#ifndef COURSE_WORK_COLORS_H
#define COURSE_WORK_COLORS_H

extern const int
    COLOR_BLACK,
    COLOR_BLUE,
    COLOR_GREEN,
    COLOR_CYAN,
    COLOR_RED,
    COLOR_MAGENTA,
    COLOR_BROWN,
    COLOR_LIGHT_GRAY,
    COLOR_DARK_GRAY,
    COLOR_LIGHT_BLUE,
    COLOR_LIGHT_GREEN,
    COLOR_LIGHT_CYAN,
    COLOR_LIGHT_RED,
    COLOR_LIGHT_MAGENTA,
    COLOR_YELLOW,
    COLOR_WHITE,
    DEFAULT_CHAR_COLOR,
    DEFAULT_BACKGROUND_COLOR;

#endif //COURSE_WORK_COLORS_H
