#ifndef COURSE_WORK_BADCOMPAREOPERATORCOMMANDARGUMENTEXCEPTION_H
#define COURSE_WORK_BADCOMPAREOPERATORCOMMANDARGUMENTEXCEPTION_H


#include "BadInputException.h"

class BadCompareOperatorException : public BadInputException { };


#endif //COURSE_WORK_BADCOMPAREOPERATORCOMMANDARGUMENTEXCEPTION_H
