#ifndef COURSE_WORK_BADCOMPAREOPERATORCOMMANDARGUMENTEXCEPTION_H
#define COURSE_WORK_BADCOMPAREOPERATORCOMMANDARGUMENTEXCEPTION_H


#include "Exception.h"

class BadCompareOperatorCommandArgumentException : public Exception { };


#endif //COURSE_WORK_BADCOMPAREOPERATORCOMMANDARGUMENTEXCEPTION_H
